name: provide-repo-access-for-teams
on:
  workflow_dispatch:
    inputs:
      organization:
        type: string
        default: 'devwithkrishna'
        description: "The GitHub organization where the team will be provided access to."
        required: true
      team_name:
        description: "The name of the github team."
        type: string
        required: true
      repo_names:
        description: "repositories to be added to the teams"
        required: true
      permission:
        type: choice
        options:
          - pull
          - push
          - triage
          - maintain
          - admin
      

run-name: ${{ github.actor }} - providing access to -${{ inputs.team_name }} - ${{inputs.team_name}}
jobs:
  provide-repo-access-for-teams:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: execute the program
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          bash provide_repo_access_for_teams.sh "${{ inputs.organization }}" "${{ inputs.team_name }}" "${{ inputs.repo_names }}" "${{ inputs.permission }}"

  
